# -*- coding: utf-8 -*-
"""세미나 과제Python_김지수.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DiJ7gaEOs-HeYKN91QzThIwp8a8Xp3oP
"""

#물의 양을 계산하는 함수 정의
def max_water_volume(heights):
  if not heights:
    return 0

  left, right = 0, len(heights)-1
  max_left, max_right = 0, 0
  water_volume = 0

  while left<right :
    if heights[left] < heights[right]:
      if heights[left] >= max_left:
        max_left = heights[left]
      else:
        water_volume += max_left - heights[left]
      left += 1
    else:
      if heights[right]>= max_right:
        max_right = heights[right]
      else:
        water_volume += max_right - heights[right]
      right -= 1
  return water_volume

#예시
heights_1 = [1,4,2,0,1,2,3,4,5,2,1,5,0,1]
heights_2 = [3,2,1,0,3,0,1,3,8]
heights_3 = [1,3,6,9,3,2,3,7,1,1,1,0]

volume_1 = max_water_volume(heights_1)
volume_2 = max_water_volume(heights_2)
volume_3 = max_water_volume(heights_3)

print(volume_1, volume_2, volume_3)